# Generated by Django 5.1.1 on 2024-11-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_gymowner_contact_no_gymuser_contact_no'),
        ('trainer', '0002_workoutplan_delete_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutPlan',
            new_name='Plan',
        ),
    ]
