# Generated by Django 5.1.1 on 2024-10-10 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymOwner',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gym_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='gym_instance',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='gym_instance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='baseuser_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trainer_instance',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gym_id',
            field=models.ForeignKey(default=0.002997002997002997, on_delete=django.db.models.deletion.CASCADE, to='accounts.gymowner'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainer')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
