# Generated by Django 5.1.1 on 2024-11-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='gym_id',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='accounts.gymowner'),
        ),
    ]
