# Generated by Django 5.1.1 on 2024-11-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_trainer_gym_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='gym_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gymowner'),
        ),
    ]
