# Generated by Django 5.1.1 on 2024-11-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_trainer_gym_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='gym_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gymowner'),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='trainer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainer'),
        ),
    ]
