# Generated by Django 5.1.1 on 2024-11-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_gymowner_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymowner',
            name='contact',
            field=models.CharField(blank=True, default='00000000', max_length=10, null=True),
        ),
    ]
