# Generated by Django 5.1.1 on 2024-11-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_trainer_contact_no_alter_trainer_gym_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymowner',
            name='contact_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='contact_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
