# Generated by Django 5.1.1 on 2024-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_baseuser_contact_alter_gymuser_gym_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymowner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
