# Generated by Django 5.1.1 on 2024-11-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_gymowner_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
