# Generated by Django 5.1.1 on 2024-11-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_trainer_gym_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NA', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gymowner')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainer')),
            ],
        ),
    ]
