# Generated by Django 5.1.1 on 2024-11-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymOwner', '0002_userrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
